language: node_js
node_js:
  - 'stable'
cache:
directories:
  - 'node_modules'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
notifications:
  webhooks: https://coveralls.io/webhook
